Add module text-classification
ArDoCo/Core pull request #137
Opened 2022-07-26 13:22 UTC by Gram21

Done by @Lin0pan

2022-09-03 09:11 UTC, Lin0pan commented
ready to review

2022-09-05 07:47 UTC, dfuchss requested changes
Found some things that needs to be addressed before merging

2022-09-05 07:47 UTC, dfuchss commented on text-classification/pom.xml
> +        <relativePath>../pom.xml</relativePath>
```suggestion
```

2022-09-05 07:47 UTC, dfuchss commented on text-classification/pom.xml
> +    </repositories>
```suggestion
```

2022-09-05 07:47 UTC, dfuchss commented on text-classification/pom.xml
> +    <artifactId>text-classification</artifactId>
Needs to be fixed

2022-09-05 07:47 UTC, dfuchss commented on text-classification/pom.xml
> +            <version>1.1.1</version>
We use jackson elsewhere (afaik)

2022-09-05 16:23 UTC, dfuchss commented
@sonatype-lift help

2022-09-05 16:23 UTC, dfuchss commented on text-classification/src/main/java/docker/helper/ExecuteCmd.java
> +            Process process = Runtime.getRuntime().exec(command);
@sonatype-lift help

2022-09-14 19:56 UTC, dfuchss commented
@Gram21 @Lin0pan maybe we have to merge `main` to the branch? The diff is not readable :)

2022-09-16 14:05 UTC, dfuchss commented on text-classification/pom.xml
> +    </dependency>
Versions are managed in the InFormALin parent

2022-10-11 16:37 UTC, merged

2022-10-11 16:39 UTC, Gram21 commented
Merging for now to the branch and working directly on it.