Initial phrase mappings
ArDoCo/Core pull request #145
Opened 2022-08-05 08:18 UTC by Hossiphi

Currently enabled: 
* when a word is added to the text state, a noun mapping and a phrase mapping is created
* noun mappings are stored in a set, compared via their reference and phrases
* phrase mappings are also stored in a set, compared via their phrases
* noun mappings and phrase mappings are not directly connected - the relation between them can only be obtained with the text state - this reduces effort for consistency control
* the text state merges no longer noun mappings - the text stage should be used to identify the relevant words. Noun mappings should be merged by later agents that run when it can be ensured that the whole text was read by all noun mapping creating agents. Whether this is at the end of the text stage or at the beginning of the recommendation stage has to be discussed.
* the mapping combiner agent (currently at the end of the text stage) merges noun mappings that are similar/ textually equal and have similar/ the same phrase mapping

Defintions and invariants: 
* every noun mapping has exactly one phrase mapping
* a phrase mapping has at least one noun mapping
* every word that was added to the text state is converted/ added to a noun mapping that can be obtained with getNounMappingByWord(word). For its phrase mapping this works analogue.

Future work: 
* noun mappings are only created by the text state- every agent that works explicitly on noun mappings is moved to the recommendation stage
* reflect invariants in the implementation
* move merging actions of existing text agents to separate agents
* discuss the position/ stage of merging agents
* create recommended instances based on phrase mappings

By adding the new merge mentality the approach should recover its recall. Currently, the recall is very low because only small amounts of (currently not merged) words are connected to model instances.

2022-08-29 10:57 UTC, dfuchss requested changes
Just a short review for the future :)

2022-08-29 10:57 UTC, dfuchss commented on inconsistency-detection/src/test/java/edu/kit/kastel/mcse/ardoco/core/inconsistency/types/AbstractInconsistencyTypeTest.java
> +        }
```suggestion
        public Phrase getPhrase() {
            throw new UnsupportedOperationException();
        }
```

2022-08-29 10:57 UTC, dfuchss commented on text-extraction/pom.xml
> +      <version>4.4.0</version>
The version is fixed somewere

2022-08-29 10:57 UTC, dfuchss commented on text-extraction/src/main/java/edu/kit/kastel/mcse/ardoco/core/textextraction/DefaultTextStateStrategy.java
> +                var otherNounMapping2 = textState.getNounMappings().select(nm -> nm.getWords().containsAllIterable(finalOtherNounMapping.getWords()));
Naming :)

2022-08-29 10:57 UTC, dfuchss commented on text-extraction/src/main/java/edu/kit/kastel/mcse/ardoco/core/textextraction/NounMappingImpl.java
> +        return reference;
String.join

2022-08-29 10:57 UTC, dfuchss commented on text-extraction/src/main/java/edu/kit/kastel/mcse/ardoco/core/textextraction/NounMappingImpl.java
> +    public boolean isTheSameAs(NounMapping other) {
isTheSameAs should be equals()

2022-09-02 08:45 UTC, dfuchss commented on text-extraction/src/main/java/edu/kit/kastel/mcse/ardoco/core/textextraction/NounMappingImpl.java
> +    public boolean isTheSameAs(NounMapping other) {
Or don't call it isTheSameAs .. e.g., hasSameReference(NM other)

2022-09-02 08:46 UTC, dfuchss commented on text-extraction/src/main/java/edu/kit/kastel/mcse/ardoco/core/textextraction/NounMappingImpl.java
> +    public boolean isTheSameAs(NounMapping other) {
And we should maybe drop every "equals" in Noun and Phrase Mapping as there are not "the one equals"

2022-09-02 09:01 UTC, Hossiphi commented on connection-generator/src/main/java/edu/kit/kastel/mcse/ardoco/core/connectiongenerator/extractors/NameTypeConnectionExtractor.java
> +            NounMapping preMapping = textExtractionState.getNounMappingByWord(pre);
I think it's pretty obvious that preWord stands for previousWord. (They were formerly also called preWords and also the method to obtain them is named "getPreWord()".) I will specify "pre" to "preWord", but I would like to keep it as before as preWord and avoid to make the name longer than needed.
Yes, I think the preWords can be null.

2022-09-02 09:19 UTC, dfuchss commented on connection-generator/src/main/java/edu/kit/kastel/mcse/ardoco/core/connectiongenerator/extractors/NameTypeConnectionExtractor.java
> +            NounMapping preMapping = textExtractionState.getNounMappingByWord(pre);
that was more about the type of "pre" .. "preWord" directly implies that the type of pre is "Word" since "var" is used.

2022-09-02 09:44 UTC, dfuchss requested changes
In general, it looks good. But I've some remarks

2022-09-02 09:44 UTC, dfuchss commented on common/src/main/java/edu/kit/kastel/mcse/ardoco/core/api/data/recommendationgenerator/RecommendedInstance.java
> +    ImmutableSet<Integer> getSentenceNumbers();
ImmutableSortedSet ?

2022-09-02 09:44 UTC, dfuchss commented on common/src/main/java/edu/kit/kastel/mcse/ardoco/core/api/data/textextraction/NounMapping.java
> +    boolean isCompound();
Docs fo isCompound

2022-09-02 09:44 UTC, dfuchss commented on common/src/main/java/edu/kit/kastel/mcse/ardoco/core/api/data/textextraction/PhraseMapping.java
> +    void removePhrase(Phrase phrase);
remove is still possible

2022-09-02 09:44 UTC, dfuchss commented on common/src/main/java/edu/kit/kastel/mcse/ardoco/core/api/data/textextraction/TextState.java
> +    void mergeNounMappings(NounMapping nounMapping, NounMapping otherNounMapping, Claimant claimant, ImmutableList<Word> referenceWords);
Maybe explain what the merge does.
Should this return the new nounMapping?

2022-09-02 09:44 UTC, dfuchss commented on common/src/main/java/edu/kit/kastel/mcse/ardoco/core/api/data/textextraction/TextState.java
> +    boolean isWordContainedByMappingKind(Word word, MappingKind kind);
Rename / Explain. isWordContainedInNounMappingOfKind ?

2022-09-02 09:44 UTC, dfuchss commented on common/src/main/java/edu/kit/kastel/mcse/ardoco/core/common/util/SimilarityUtils.java
> +                                        .size(), recommendedInstanceNameList.size()) >= similarity) {
This is really complex. I would suggest to create boolean variables for the cases that are checked here; e.g.,

boolean similarNames = areWordsSimilar(instance.getFullName(), ri.getName());
boolean similarInstanceNames = ....

2022-09-02 09:44 UTC, dfuchss commented on common/src/main/java/edu/kit/kastel/mcse/ardoco/core/common/util/SimilarityUtils.java
> +                                        longestNameSplit.size(), surfaceFormWords.size()) >= similarity) {
Same as above. We should explain what we are doing here by good variable names

2022-09-02 09:44 UTC, dfuchss commented on common/src/main/java/edu/kit/kastel/mcse/ardoco/core/common/util/SimilarityUtils.java
> +    //TODO: Move to common utilities
Resolve TODO

2022-09-02 09:44 UTC, dfuchss commented on common/src/main/java/edu/kit/kastel/mcse/ardoco/core/common/util/SimilarityUtils.java
> +        Map<CharSequence, Integer> vector2 = phraseVector2.entrySet().stream().collect(Collectors.toMap(e -> e.getKey().getText(), Map.Entry::getValue));
Typically you would use something like "firstVector" and "secondVector" to be sure that they are not accidentally swapped

2022-09-02 09:44 UTC, dfuchss commented on common/src/main/java/edu/kit/kastel/mcse/ardoco/core/common/util/SimilarityUtils.java
> +    public enum PhraseMappingAggregatorStrategy implements ToDoubleBiFunction<PhraseMapping, PhraseMapping> {
Move to File if public

2022-09-02 09:44 UTC, dfuchss commented on recommendation-generator/src/main/java/edu/kit/kastel/mcse/ardoco/core/recommendationgenerator/extractors/CompoundRecommendationExtractor.java
> +            if (nounMapping.isCompound()) {
Just seen here. can a nounmapping be a "compound" or are the compounds the "words"

2022-09-02 09:44 UTC, dfuchss commented on text-extraction/src/main/java/edu/kit/kastel/mcse/ardoco/core/textextraction/DefaultTextStateStrategy.java
> +public abstract class DefaultTextStateStrategy implements TextStateStrategy {
rename to "TextStateStrategyBase"

2022-09-02 09:44 UTC, dfuchss commented on text-extraction/src/main/java/edu/kit/kastel/mcse/ardoco/core/textextraction/PhraseConcerningTextStateStrategy.java
> +        if (nounMappingsWithWord.size() > 0) {
!isEmpty()

2022-09-02 09:44 UTC, dfuchss commented on text-extraction/src/main/java/edu/kit/kastel/mcse/ardoco/core/textextraction/PhraseConcerningTextStateStrategy.java
> +            if (surfaceForms == null || surfaceForms.equals(nounMapping.getSurfaceForms())) {
equals for lists: check

2022-09-02 09:44 UTC, dfuchss commented on text-extraction/src/main/java/edu/kit/kastel/mcse/ardoco/core/textextraction/PhraseConcerningTextStateStrategy.java
> +    public NounMapping mergeNounMappings(NounMapping nounMapping, NounMapping nounMapping2, ImmutableList<Word> referenceWords, String reference,
naming:

one is the existing noun mapping and one dispos..... (check naming with original state?)

2022-09-02 09:44 UTC, dfuchss commented on text-extraction/src/main/java/edu/kit/kastel/mcse/ardoco/core/textextraction/TextStateImpl.java
> +        return getNounMappings().select(nm -> phraseMapping.getPhrases().toImmutableSet().equals(nm.getPhrases()));
check equals here.

2022-09-02 09:44 UTC, dfuchss commented on text-extraction/src/test/java/edu/kit/kastel/mcse/ardoco/core/textextraction/agents/MappingCombinerTest.java
> +class MappingCombinerTest implements Claimant {
Maybe add some docs to the tests for later

2022-09-05 17:25 UTC, dfuchss approved these changes
@Gram21 if you do not find any critical issue, this should be ready for merge

2022-09-06 11:37 UTC, merged