Add informal diagram consistency pipeline steps
ArDoCo/Core pull request #308
Opened 2023-12-05 12:15 UTC by jeanpmathes

This PR adds a module containing steps to find trace links between diagrams and models (architecture, code). Addionally, the code model is adapted to contain more information, including references to used types and parent classes for nested classes.

2023-12-05 12:20 UTC, dfuchss requested changes
Some comments before CI build :)

2023-12-05 12:20 UTC, dfuchss commented on stages/diagram-consistency/pom.xml
> +    </properties>
Managed by parent :)

2023-12-05 12:20 UTC, dfuchss commented on stages/diagram-consistency/pom.xml
> +            <version>0.26.0.local-SNAPSHOT</version>
```suggestion
            <version>${revision}</version>
```

2023-12-05 12:20 UTC, dfuchss commented on stages/diagram-consistency/pom.xml
> +        </dependency>
See above :)

2023-12-05 12:20 UTC, dfuchss commented on stages/diagram-consistency/pom.xml
> +            <version>2.15.2</version>
Version managed by parent

2023-12-05 12:20 UTC, dfuchss commented on stages/diagram-consistency/pom.xml
> +            <version>2.15.2</version>
Version managed by parent

2023-12-05 12:20 UTC, dfuchss commented on stages/diagram-consistency/pom.xml
> +            <scope>test</scope>
See pom.xml in other tests. Version also managed

2023-12-05 12:20 UTC, dfuchss commented on stages/diagram-consistency/pom.xml
> +    <groupId>edu.kit.kastel.kit.mcse.ardoco.diagramconsistency</groupId>
Adapt Group id similar to other modules :)

2023-12-05 12:22 UTC, dfuchss commented on framework/common/pom.xml
> +      </dependency>
Add version of jgraph to property in outer pom.xml and use it for all modules

2023-12-05 23:42 UTC, dfuchss commented on framework/common/pom.xml
> +      <scope>compile</scope>
```suggestion
```

2023-12-05 23:45 UTC, dfuchss commented
Two points:
* Could you run `mvn spotless:apply` once ?
* Could you add a PR to ArDoCo/Benchmark instead of changing the benchmark in this repository directly :)

2023-12-06 09:35 UTC, jeanpmathes commented
PR in benchmark is here: https://github.com/ArDoCo/Benchmark/pull/12

2023-12-06 10:04 UTC, dfuchss commented
Thanks :) I've updated the benchmark. Let's wait for the CI

2023-12-06 10:12 UTC, dfuchss commented
@jeanpmathes can you look at 

```
Error:  Failures: 
Error:    DiagramLoadingTest.loadStageOne:86->EvaluationBase.getCodeModel:106 expected: not <null>
Error:    DiagramConsistencyTest.evaluateStage1VersionFinalLevenshtein:244->assertStage1Result:250 expected: <0.36> but was: <0.08>
Error:  Errors: 
Error:    DiagramConsistencyTest.evaluateAllStages:573->runAndEvaluateStage3:615 » NullPointer
[INFO] 
Error:  Tests run: 125, Failures: 2, Errors: 1, Skipped: 37
```

2023-12-06 14:38 UTC, jeanpmathes commented
The commits might fix the first failure, but I am not sure as I can't reproduce it. For the other two problems I am still looking for a reason.

2023-12-06 16:05 UTC, dfuchss commented
Maybe you have to clear some AppData/ArDoCo folders.

2023-12-08 14:17 UTC, dfuchss commented
@jeanpmathes in https://github.com/ArDoCo/Core/pull/315 we beautified the JSON of the Code Model. Could you regenerate the Code Model (adapted version) and create another PR in benchmark again :) Then the review should be easy.

2023-12-11 15:35 UTC, dfuchss commented on framework/common/src/main/java/edu/kit/kastel/mcse/ardoco/core/api/diagramconsistency/common/Edge.java
> +    public enum Label {
Extract Enum to own file :)

2023-12-14 17:48 UTC, jeanpmathes commented
Something seems wrong with coverage calculation, it fails even before verify is done. Checking coverage locally leads to a higher value, which also makes sense because multiple of the tests run the entire pipeline that is added.

2023-12-14 19:38 UTC, dfuchss commented
It works now :) I'll have a look at the code again but I think it will be good 👍

2023-12-15 10:52 UTC, dfuchss approved these changes
In summary, it looks good to me. Thanks a lot.

2023-12-15 10:52 UTC, dfuchss commented on framework/common/src/main/java/edu/kit/kastel/mcse/ardoco/core/api/diagramconsistency/common/TextSimilarity.java
> +    private static final Map<UnorderedPair<String, String>, Double> CACHE_FOR_BASIC_FUNCTION = new java.util.LinkedHashMap<>();
Could we use sorted maps here. Then we could remove `@Deterministic`

2023-12-15 10:52 UTC, dfuchss commented on stages/diagram-consistency/src/test/java/edu/kit/kastel/mcse/ardoco/core/diagramconsistency/evaluation/EvaluationTestBase.java
> +            String repository = project.getSourceProject().getCodeRepository();
I'll have a look here. The loading should be handled by the enum (internally)

2023-12-20 14:00 UTC, Gram21 approved these changes

2023-12-20 14:00 UTC, Gram21 commented on stages/model-provider/src/test/resources/interface/edu/AClass.java
>  // import edu.drei.OtherInterface;
Even if it was there before, maybe remove this commented out import

2023-12-21 20:18 UTC, dfuchss commented
@jeanpmathes thanks for the PR. Well done :) I'll merge it now !

2023-12-21 20:19 UTC, merged